platform :ios, '8.0'

pod 'PBJVision'
pod 'Parse', '1.7.1'
pod 'ParseFacebookUtils'
#pod 'Facebook-iOS-SDK', '3.23.2'
pod 'GSProgressHUD'
pod 'AFNetworking'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'